name: My First Workflow

# Run workflow whenever code is pushed
on:
  push:

jobs:
  build:
    # Create temporary Ubuntu machine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build